name: achiever_app
description: Todo list app centered on positive reinforcement.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.9.2
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  flutter_icons: ^1.1.0
  gradient_text: ^1.0.2
  vibration: ^1.7.3

  # hydrated_bloc: 6.1.0
  # path_provider: ^1.6.27
  # uuid: ^2.2.2
  # json_annotation: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  json_serializable: ^3.5.1
  mockito: ^4.1.4

  # build_runner:

flutter:
  uses-material-design: true